const fs = require('node:fs');
const path = require('node:path');

//Create a generated-version.ts file with the current cli version from package.json before the build process starts

const pkg = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'package.json'), 'utf-8')
);

const outDir = path.join(__dirname, 'src/application/configuration');
const outPath = path.join(
  __dirname,
  'src/application/configuration/generated-version.ts'
);

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  outPath,
  `// Auto-generated by generate-version.js — do not edit\nexport const CLI_VERSION = ${JSON.stringify(pkg.version)};\n`
);
